### ISSUE TITLE
Sea level pressure

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-v4-Configurations#23]
R4 is forced with high frequency sea level pressure fields,right?  We should add this pressure field as part of the product.  Probably as a an EXF field.  

@owang01

**Comment by owang01** [comment]
Definitely as a forcing field.

**Comment by ifenty** [comment]
@owang01 

It’s true that the high frequency sea level pressure field is not adjusted but that’s not a requirement for EXF fields (for example, see runoff, wind speed).  

I think we should include atmospheric pressure as both a forcing field (of course) and an EXF field.   That way someone can easily include this forcing field in their analysis (unlike the raw forcing fields which are not easy to load/analyze).

**Comment by ifenty** [comment]
@owang01 SLP is now an output field, correct?

**Comment by owang01** [comment]
SLP (called EXFpress) is an output field.
