### ISSUE TITLE
Adjoint runs fail with salt/tempVertAdvScheme = 33

### ISSUE THREAD

**Issue by emmomp** [ECCO-GROUP/ECCO-v4-Configurations#39]
Adjoint runs fail during the forward portion of the run (i.e. during calculation of the cost function) with CALC_R_STAR errors when I tried a run with salt/tempAdvScheme=33 and didn't specify the VertAdvScheme (set to 3 in ECCO setup). Not sure if this is expected behaviour. Cost function is a simple global temperature sum.

Background: I've spun up a version of the LLC grid forced by CORE2 normal year fields (setup verifications/global_oce_llc90/) which has various differences in the data namelists when compared to the ECCO standard setup. Adjoint runs fail with current options. By comparison with the ECCO parameters and several test runs I determined that it is the differing vertical advection schemes causing the failure. Specifying vertAdvScheme=3 leads to a successful run.

**Comment by emmomp** [comment]
p.s. also if this is the wrong place to raise this issue please let me know!

**Comment by gaelforget** [comment]
> p.s. also if this is the wrong place to raise this issue please let me know!

This and the @mitgcm issue tracker seem like the best place to get help on this. I cross referenced it in https://github.com/MITgcm/MITgcm/issues/329 in case someone on that side might be able to jump in and might not follow this org

**Comment by emmomp** [comment]
Apologies - this turns out not to be an Adjoint issue. Any forward run fails similarly with  salt/tempAdvScheme=33 and salt/tempImplVertAdv=.TRUE. It runs successfully with vertAdvScheme=3. This may be a feature of the implicit vertical advection, there is no documentation I could find.
