### ISSUE TITLE
Shouldn't we mention issue tracker in main README.md ?

### ISSUE THREAD

**Issue by gaelforget** [ECCO-GROUP/ECCO-v4-Configurations#47]
I definitely see the value in

`If user support is needed, please contact ecco-support@mit.edu or mitgcm-support@mit.edu`

but shouldn't we also (or even primarily?) point folks to the GitHub issue tracker in this repo?

This is the new standard way that lots of people deal with user support I feel. Just a thought

**Comment by ifenty** [comment]
@gaelforget yes.  added
