### ISSUE TITLE
add SSH and OBP as diagnostics

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-v4-Configurations#6]
@owang01 

Currently SSH and OBP are calculated offline to implement the Greatbatch correction (Greatbach 1994) and the sea ice load correction.  I think we should add SSH and OBP as diagnostics to save users from having to do these  correction themselves. The reason is that these time-varying Greatbatch corrections are not currently output as a separate file -- they are printed in STDOUT.  A user therefore has to know how to parse out the correction term from STDOUT  which, AFAIK,  is not documented.  

References:
Greatbatch 1994., A note on the representation of steric sea level in models that conserve volume rather than mass.  https://doi.org/10.1029/94JC00847

**Comment by rmponte** [comment]
Good to have global mean SSH, OBP as separate output, as long as it is documented and people know how to use it. In our case the sea level term does account for the changes in freshwater but not global mean steric effects. So you might want to explicitly say how to do the correction from the two terms provided.

**Comment by ifenty** [comment]
I believe @owang01 has completed this issue.  Ou, can you confirm.  Could you share the text (‘long names’?) that you’ve prepared that explain how SSH differs from ETAN and how OBP differ from PHIBOT and OBPNOAP?

**Comment by owang01** [comment]
I output SSH, OBP and a few related diagnostic output variables for the coming ECCO Version 4, Release 4. Here is the snippet of the updated available_diagnostics.log. 

    24 |SSH     |  1 |       |SM      M1|m               |ETAN Adjusted with Global Steric Height Change and Sea-ice Load
    25 |SSHIB   |  1 |       |SM      M1|m               |Inverted Barometer SSH
    26 |SSHDYN  |  1 |       |SM      M1|m               |Dynamic SSH (SSH-SSHIB)
    77 |OBP     |  1 |       |SM      M1|m^2/s^2         |Bottom Pressure Pot.(p/rho) Anomaly Adjusted with Global Steric Height Change
    78 |OBPNOPAB|  1 |       |SM      M1|m^2/s^2         |OBP with Global Mean Air-Pressure Removed

**Comment by ifenty** [comment]
Thanks Ou.  I think we need to have more text somewhere that describes how these fields differ.   For example, the description that SSH is ‘adjusted with global steric height change and sea-ice load’ doesn’t actually describe what is done.   I think the description for OBP is similarly cryptic: ‘adjusted with global steric height change’?

**Comment by ifenty** [comment]
The SSH diagnostic should be 
SSH : Dynamic SSH, SSH  without IB
