### ISSUE TITLE
regeneration of netcdf

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-v4-Configurations#7]
Feedback from PO.DAAC

https://podaac.jpl.nasa.gov/PO.DAAC_DataManagementPractices

1. Add  ```time_coverage_resolution``` to native grid fields, P1M (monthly) or P1D (daily).  

1. Fix ``time_coverage_resolution`` on the interpolated files (remove extra "\" fields)

1. Remove all of our custom standard names : http://cfconventions.org/Data/cf-standard-names/67/build/cf-standard-name-table.html

1. Add comments defining what all the variables are. Some are obvious, but not all of them, especially the ancillary file.  Add this information to our "variable" JSON files.

1. Remove non-essential grid information from the native grid files.  

1. Add metadata comment to every netcdf file telling the users that the grid information is in the netcdf grid file.

1. UUID to each file

1. Valid range is an ARRAY

1. Time needs standard NAME

1. What is SWAP dimenion?

1. Use valid range (min, max)

1. SSH use Sea surface height above geoid

1. Use comments instead of 'LONG NAME'

1. Find out what 'grid mapping' means

1. use same time format in time coverage start, time coverage end and other places.  ** whether to have 'T' included or not.

1. geospatial vertical units 'm'

1. change canonical units from (kg/m^3/)m to format: kg m-3 m-1, and degree_C

1. use cell bounds

**Comment by ifenty** [comment]
@owang01 
Fields that need to be added:

**volume budget**
- sIceLoad snapshots (to calculate \partial ETAN+sea ice + snow volume / \partial t$

**momentum budget** (pending confirmation from Mazloff)
- UVEL, VVEL, WVEL snapshots (to calculate $\partial momentum / \partial t$)
- UVELMASS, VVELMASS snapshots [would these be useful too since they are the are scaled by s*?]
- Um_Diss, Vm_Diss, (momentum tendency from Dissipation)
- Um_Advec, Vm_Advec, (momentum tendency from Advection)
- Um_Cori , Vm_Cori,  (momentum tendency from Coriolis)
 - Um_Ext,  Vm_Ext, (external forcing)
- TOTUTEND, TOTVTEND (these are actual tendencies)
- VISrI_Um, VISrI_Vm (vertical viscous flux of momentum)

**Comment by owang01** [comment]
@ifenty 

The sIceLoad snapshots can be simply calculated by summing SIheff and SIsnow snapshots (weighted by their own density). Both SIheff and SIsnow snapshots are available https://ecco.jpl.nasa.gov/drive/files/Version4/Release4/nctiles_monthly_snapshots for monthly interval and https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_90/ECCOv4/Release4/nctiles_daily_snapshots for daily interval.

**Comment by ifenty** [comment]
We also need the LAST snapshots of all the snapshot fields (20XX-12-31)

**Comment by ifenty** [comment]
** 2019-01-24 **

**issue 1:**
latitude and longitude and depth need to have the 'axis' string attributes
axis = 'X'
axis = 'Y'
axis = 'Z'

**issue 2**
 can get suppress the variable of i,j,k?

**issue 3**
can the order of 'coordinates' be reconciled with the order of the actual array

** issue 4**
timestep should have better description (number of hours) 

** issue 5 "
time_bnds needs to say days since 1992-01-01
