### ISSUE TITLE
End-of-file namelist errors on two Cray HPC platforms

### ISSUE THREAD

**Issue by DanJonesOcean** [ECCO-GROUP/ECCO-v4-Configurations#73]
Hello,

I am attempting to reproduce ECCOv4-r4 on two Cray HPC platforms, namely on both ARCHER and the new ARCHER2 for benchmarking purposes. I am using this document as guidance:

[https://ecco-group.org/docs/v4r4_reproduction_howto.pdf](https://ecco-group.org/docs/v4r4_reproduction_howto.pdf)

The code compiles without issue. For context, I used the Cray compiler on ARCHER and the gnu compiler on ARCHER2. (We are still working out how to use the Cray compiler for MITgcm on ARCHER2. It's a brand new machine.)

I received end-of-file errors when running the code as-is, and I traced these errors to the use of "&" characters as end-of-namelist characters in some of the data* files. That is, in some of the namelists, the "/" character is the end-of-namelist marker, whereas in others, it is the "&" character. 

After I changed all of the end-of-namelist characters to "/", the code ran without error. 

I'm guessing that you probably don't want to change your configurations, but it might be a good idea to note this somewhere in the documentation. I'm happy to contribute in some way if you like - please let me know how you would like to proceed.

**Comment by DanJonesOcean** [comment]
An update on this: on ARCHER, I was able to avoid end-of-file runtime errors by first converting all the namelist files to unix formatting using the ``dos2unix`` command. As downloaded from GitHub, a few of the data files appear to have dos formatting, which causes end-of-file errors when running on the Cray ARCHER  or ARCHER2 platforms.  

It's possible that this dos formatting issue may be the root cause of the end-of-file errors, as opposed to the end-of-namelist characters that I mentioned when raising this issue. Either way, could I gently suggest that it may be a good idea to use unix formatting and consistent end-of-namelist characters in the source code? Apologies if I've missed a reason for the current formatting of the files as they currently exist in the repository.

Thanks for any help/guidance/suggestions you can provide.

**Comment by ifenty** [comment]
@DanJonesOcean Thank you for pointing out these issues Dan.

I changed all terminating characters to '/' and applied dos2unix to all files in the v4r4 namelist directory and the v4r5 devel namelist directory. 

#76 #77
